### PR TITLE
WIP: Work around mutating style elements

### PR DESCRIPTION
**Pull request by tedpennings**
This reverts commit 386e0a5a4b9b106b3ee85aba8e512470393c4b70.

Trying this to mitigate a few styling failures

### CODE REVIEW

**Comment by tedpennings** [comment]
Doh, I meant to put that in our Lightstep fork before pushing a notification to you! Sorry about that 😳 

We're seeing an issue where the styles are different in 1.8.0. We were on 1.7.2. That seems like the only significant change to style processing between versions. My theory is that the `element.__happoAlreadyProcessed` logic isn't picking up changes to the style elements, causing incorrect screenshots. I'm not sure why that would be happening. The failures are where we use `jss` with `material-ui`. I'm not sure if `jss` is mutating the existing `<style>` elements in the DOM, and the changes aren't being picked up.

If this theory is true, we can either change our `jss` config -- I think it's the `cache` option -- or we could continue with this PR **AS A FLAG**, not as a revert. (Sorry that this PR came in that way -- it was eaiser for testing purposes.) I'm not sure if the big bundles you saw, @trotzig, were coming from the Lightstep Cypress tests or elsewhere. I'm also not sure what performance gains (if any) we are getting from `<style>` mutation.

@dcarrot2 and I are investigating this and don't need anything right now.

**Comment by trotzig** [comment]
I had a feeling the change I made in 1.8.0 could cause issues. Sorry for the trouble but I'm glad you have a fix in mind. I'm going to put this behind some kind of feature flag, as it's an important fix for some test suites.

**Comment by trotzig** [comment]
I'm working on putting the new behavior behind a flag in https://github.com/happo/happo-cypress/pull/38. If you want to try things without the `element.__happoAlreadyProcessed` logic, you can try installing `happo-cypress@1.9.0-rc.1`.

**Comment by tedpennings** [comment]
Thanks! I'm closing this PR in favor of #38 and the email thread with @dcarrot2

**Pull request closed without merging**
